import type { PlayerMode, StrategyScoringWeights } from '../types/totym';

// Initial heuristic weights for transparent strategy scoring.
// These are editable initial heuristics, not official game values or win-rate data.
// Adjust these numbers to tune the scoring model without changing scorer logic.
export const DEFAULT_STRATEGY_SCORING_WEIGHTS: StrategyScoringWeights = {
  // A. Ascension Consistency — base 20, clamped 0–100
  ascensionConsistency: {
    base: 20,
    completeCreatureCore: 20,
    clanConcentration12: 10,
    clanConcentration3: 5,
    clanConcentration45: 0,
    blessingTotemLockPerCreature: 8,
    blessingTotemLockMax: 8,
    extraTotemLockPerQty: 4,
    extraTotemLockMax: 12,
    extraWorshipActionPerQty: 3,
    extraWorshipActionMax: 12,
    extraTarotActionPerQty: 3,
    extraTarotActionMax: 9,
    drawPerQty: 2,
    drawMax: 10,
    redrawPerQty: 2,
    redrawMax: 6,
    lookArrangePerQty: 2,
    lookArrangeMax: 6,
    worshipReq25OrLess: 5,
    worshipReq26To30: 2,
    worshipReqOver30: 0,
    fewerThan5Creatures: -10,
    duplicateCreatures: -12,
    perClanAbove3: -2,
    fiveClansPenalty: -5,
    tarotFewerThan20: -5,
    tarotFewerThan10: -8,
    worshipFewerThan20: -8,
    worshipZero: -10,
    unknownCardIds: -5,
  },
  // B. Disruption & Control — base 0, clamped 0–100
  disruptionControl: {
    base: 0,
    blockDrawPerQty: 4,
    blockDrawMax: 12,
    blockTarotPerQty: 4,
    blockTarotMax: 12,
    blockWorshipPerQty: 4,
    blockWorshipMax: 12,
    blockTotemLockPerQty: 4,
    blockTotemLockMax: 12,
    blockImposterPerQty: 3,
    blockImposterMax: 9,
    discardPerQty: 3,
    discardMax: 15,
    revealPerQty: 2,
    revealMax: 10,
    collapseTotemPerQty: 4,
    collapseTotemMax: 12,
    cursePerQty: 3,
    curseMax: 9,
    switchCreaturePerQty: 2,
    switchCreatureMax: 10,
    skipTurnPerQty: 2,
    skipTurnMax: 8,
    skipTurnDrawPerQty: 1,
    skipTurnDrawMax: 4,
    creatureImmunityCannotBeBlockedPer: 2,
    creatureImmunityCannotBeBlockedMax: 10,
    creatureBlessingBlock1OpponentPer: 2,
    creatureBlessingBlock1OpponentMax: 10,
    creatureImmunityProtectedFromDiscardPer: 2,
    creatureImmunityProtectedFromDiscardMax: 8,
    creatureImmunityCannotBeRevealedPer: 2,
    creatureImmunityCannotBeRevealedMax: 8,
    creatureImmunityCannotBeForcedToSwitchPer: 2,
    creatureImmunityCannotBeForcedToSwitchMax: 8,
    tarotFewerThan10: -5,
    perFormatDeadTarotQty: -3,
    formatDeadTarotMax: -15,
  },
  // C. Resilience & Recovery — base 15, clamped 0–100
  resilienceRecovery: {
    base: 15,
    drawPerQty: 3,
    drawMax: 15,
    redrawPerQty: 4,
    redrawMax: 12,
    shufflePerQty: 2,
    shuffleMax: 10,
    lookArrangePerQty: 2,
    lookArrangeMax: 8,
    extraTarotActionPerQty: 2,
    extraTarotActionMax: 8,
    extraWorshipActionPerQty: 2,
    extraWorshipActionMax: 8,
    extraTotemLockPerQty: 2,
    extraTotemLockMax: 8,
    switchCreaturePerQty: 2,
    switchCreatureMax: 8,
    convertWorshipPerQty: 2,
    convertWorshipMax: 10,
    blessingRedrawEntireHand: 4,
    blessingDraw3ForTurn: 3,
    blessingLookAtTop: 2,
    blessingShuffle1Worship: 2,
    immunityHandProtectedFromDiscard: 3,
    immunityTarotTotemProtectedFromDiscard: 3,
    immunityWorshipTotemProtectedFromDiscard: 3,
    immunityWorshipTotemCannotBeDiscarded: 3,
    immunityCardDrawsCannotBeBlocked: 2,
    immunityTarotActionsCannotBeBlocked: 2,
    immunityWorshipActionsCannotBeBlocked: 2,
    immunityTotemLocksCannotBeBlocked: 2,
    immunityTurnCannotBeSkipped: 2,
    immunityCannotBeForcedToSwitch: 2,
    immunityCannotBeRevealed: 2,
    tarotFewerThan10: -5,
    noBlessingCreature: -5,
    noImmunityCreature: -5,
  },
  // D. Format Fit — base 100, clamped 0–100
  formatFit: {
    base: 100,
    twoOpponents1v1PerQty: -20,
    twoOpponents1v1Max: -80,
    reverseTurnOrder1v1PerQty: -12,
    reverseTurnOrder1v1Max: -36,
    perFormatWarning: -5,
    formatWarningMax: -30,
    noTarot: -8,
    fewerThan5Creatures: -5,
    duplicateCreatures: -10,
    // multi-player bonuses
    twoOpponentsMultiPerQty: 2,
    twoOpponentsMultiMax: 8,
    allTargetMultiPerQty: 1,
    allTargetMultiMax: 8,
    anyTargetMultiPerQty: 1,
    anyTargetMultiMax: 6,
    // 1v1 bonuses
    opponent1v1PerQty: 1,
    opponent1v1Max: 10,
    self1v1PerQty: 1,
    self1v1Max: 8,
  },
  // E. Dead-Card Risk — base 0, clamped 0–100, higher is worse
  deadCardRisk: {
    base: 0,
    twoOpponents1v1PerQty: 25,
    twoOpponents1v1Max: 75,
    reverseTurnOrder1v1PerQty: 15,
    reverseTurnOrder1v1Max: 45,
    fewerThan5UniqueCreatures: 15,
    duplicateCreatures: 20,
    worshipBelow20: 10,
    tarotBelow30: 10,
    imposterBelow5: 10,
    perUnknownCardId: 5,
    unknownCardIdMax: 25,
    deckSizeNot60: 5,
    fiveClansRisk: 5,
    coinFlipMajorityRisk: 5,
    gambleMajorityRisk: 5,
  },
  // F. Overall Lab Score — weighted combination
  overall: {
    ascensionConsistency: 0.30,
    disruptionControl: 0.20,
    resilienceRecovery: 0.20,
    formatFit: 0.30,
    deadCardRiskPenalty: 0.20,
  },
};

// Optional per-mode adjustments applied on top of default overall weights.
// These are initial heuristics, not official game values.
export const PLAYER_MODE_ADJUSTMENTS: Record<
  PlayerMode,
  Partial<StrategyScoringWeights['overall']>
> = {
  '1v1': {
    formatFit: 0.30,
    deadCardRiskPenalty: 0.25,
  },
  '3-player': {
    formatFit: 0.22,
    deadCardRiskPenalty: 0.15,
  },
  '4-player': {
    formatFit: 0.18,
    deadCardRiskPenalty: 0.12,
  },
};
